name: Pause ECS Service

on:
  workflow_dispatch:

env:
  ECS_CLUSTER_NAME: aad-fis-agent-cluster
  ECS_SERVICE_NAME: aad-fis-agent-api-service


jobs:
  call-env:
    uses: ./.github/workflows/env-vars.yaml

  pause-app:
    runs-on: self-hosted
    needs: call-env
    env:
      ECS_CLUSTER_NAME: ${{ needs.call-env.outputs.ECS_CLUSTER_NAME }}
      ECS_SERVICE_NAME: ${{ needs.call-env.outputs.ECS_SERVICE_NAME }}

    steps:
      - name: Pause ECS service
        run: |
          echo "Pausing ECS service..."
          aws ecs update-service \
              --cluster $ECS_CLUSTER_NAME \
              --service $ECS_SERVICE_NAME \
            --desired-count 0