name: Pause ECS Service

on:
  workflow_dispatch:

env:
  ECS_CLUSTER_NAME: aad-fis-agent-cluster
  ECS_SERVICE_NAME: aad-fis-agent-api-service

jobs:

  pause-app:
    runs-on: self-hosted

    steps:
      - name: Pause ECS service
        run: |
          echo "Pausing ECS service..."
          aws ecs update-service \
              --cluster $ECS_CLUSTER_NAME \
              --service $ECS_SERVICE_NAME \
            --desired-count 0