name: Resume ECS Service

on:
  workflow_dispatch:

env:
  ECS_CLUSTER_NAME: aad-fis-agent-cluster
  ECS_SERVICE_NAME: aad-fis-agent-api-service


jobs:
  resume:
    runs-on: self-hosted

    steps:
      - name: Resume ECS service
        run: |
          echo "Resuming ECS service..."
          aws ecs update-service \
              --cluster $ECS_CLUSTER_NAME \
              --service $ECS_SERVICE_NAME \
            --desired-count 1